import { FDate } from "../core/FDate";

export const MAX_PLAYERS = 16;
export const NICK_LENGTH = 18;
export const MESSAGE_LENGTH = 100;
export const PLAYER_TIMEOUT = FDate.from('1m');
export const SHIELD_TIME = FDate.from('50s');
export const SPEED_TIME = FDate.from('25s');
export const CRAZY_BOMB_TIME = FDate.from('30s');
export const MOVING_TIME = FDate.from('35s');
export const BOMB_TIME = FDate.from('2s');
export const CRAZY_BOMB_MIN = FDate.from('500');
export const CRAZY_BOMB_MAX = FDate.from('5s');
export const CRAZY_BOMB_BOOST = 5;
export const SKINS_COUNT = 52;
export const TIMEOUT_MESSAGE = FDate.from('2s');
export const TIMEOUT_RECONNECT = FDate.from('10s');
export const WAIT_FOR_LIMIT = FDate.from('15s');
export const ZONELIMIT_TIMEOUT = FDate.from('15s');
export const MAX_ADDRESS_CONNECT = 5;