name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/**'
      - '.github/workflows/main.yml'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.30

      - name: Build project
        run: bun install

      - name: Deploy Client
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "packages/client/dist/*"
          target: "/var/www/openbomber"
          strip_components: 3
          rm: true

      - name: Deploy Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "packages/server/dist/*"
          target: "/root/openbomber"
          strip_components: 3
          rm: true
        
      - name: Restart Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            pm2 delete openbomber --force --silent
            cd /root/openbomber
            echo "${{ secrets.DOTENVFILE }}" > .env
            pm2 start --name openbomber index.js
